### ISSUE TITLE
Implementing corner cutouts

### ISSUE THREAD

**Issue by Windfisch** [OpenBuilds/OpenBuilds-CAM#103]
Hello,

first of all, thanks for the awesome work on the openbuilds-cam project so far. Looks really promising!

I would like to use the OpenBuilds CAM (+CONTROL) softwares into our maker space, and am missing some features; I am able to implement them, but am not sure where to start and which is the appropriate way of discussion.

I'd like to add a feature (checkbox) to enable corner cutouts ("dogbones") to outside and inside path operations, such that not too few material is removed (but too much). Also, I'd like to add some support for holding tabs and holding tabs at user-defined positions.

Is there anything to look out for when starting? Is GitHub issues the right place for this kind of discussions, or do you have a mailing list or similar?

Best regards,
Windfisch

**Comment by petervanderwalt** [comment]
Github issues is fine.

Shoot any questions you might have but sure, happy to have someone sticking in new features. 

Mainly we do toolpathing in clipper.js - checkout the Toolpathworker (we do it in a webworker to keep frontend reactive)  https://github.com/OpenBuilds/OpenBuilds-CAM/tree/master/workers/toolpath/worker

Clipper path is used to draw previews and generate gcode from https://github.com/OpenBuilds/OpenBuilds-CAM/blob/master/js/advanced-cam-gcode.js - so key thing is to let whatever you do happen on that early level (then usually the previews and gcode just follows what happens there - thats why you'll see tabs etc is done in the worker already too) 

Current automated Tabs are around here https://github.com/OpenBuilds/OpenBuilds-CAM/blob/a3c083649364d1d88619603cd672b8f7f8681094/workers/toolpath/worker/toolpathworker.js#L475-L497 and https://github.com/OpenBuilds/OpenBuilds-CAM/blob/a3c083649364d1d88619603cd672b8f7f8681094/workers/toolpath/worker/toolpathworker.js#L641-L707 

Our dragknife toolpaths does so swivel action in the corners 

https://github.com/OpenBuilds/OpenBuilds-CAM/blob/a3c083649364d1d88619603cd672b8f7f8681094/workers/toolpath/worker/toolpathworker.js#L1499-L1534 called at https://github.com/OpenBuilds/OpenBuilds-CAM/blob/a3c083649364d1d88619603cd672b8f7f8681094/workers/toolpath/worker/toolpathworker.js#L1454-L1471

Could do something similar for your dogbones, but as an option for all routing toolpaths (not another new toolpath) - apply corner dogbones before passing it to drawClipperPaths
