### ISSUE TITLE
Todo: WebWorkers

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CAM#4]
Rewrite CAM preview render as WebWorker and integrate webworker based GCODE parser (Used in MachineDriver - pull over here)

**Comment by openbuilds-engineer** [comment]
Did some work, Gcode Preview is running in WebWorker

As of https://github.com/OpenBuilds/OpenBuilds-CAM/commit/004f5ace6fb9665866d7e0cf36a989a177ee38c4 there is a some work toward doing the toolpath calculation in WebWorker

Frontend not connected, but can play with ``` drawToolpath() ``` from toolpath.js 

Todo (thoughts for when I can work on it again)
-  Drill, Dragknife, etc still has to be brought across
-  Cannot read dom from webworker, so cannot read the "do not draw linewidth" tickbox, find other way or remove
- drawToolpath() does ALL toolpaths, need to break it up to do one at a time to do the Preview button on CAM Modal
- Get some Progress updates out of WebWorker
- Adapt UI to show Processing when its running etc
- Add drawToolpath() to the WorkSpace Parse and Import
- Remove the old advanced-cam-threegcode and advanced-cam-preview scripts

**Comment by openbuilds-engineer** [comment]
Todo (thoughts for when I can work on it again)

Drill, Dragknife, etc still has to be brought across
Cannot read dom from webworker, so cannot read the "do not draw linewidth" tickbox, find other way or remove
[x] [DONE] drawToolpath() does ALL toolpaths, need to break it up to do one at a time to do the Preview button on CAM Modal  
[x] [DONE] Get some Progress updates out of WebWorker
[x] [DONE] Adapt UI to show Processing when its running etc
[x] [DONE] Add drawToolpath() to the WorkSpace Parse and Import
Remove the old advanced-cam-threegcode and advanced-cam-preview scripts

**Comment by openbuilds-engineer** [comment]
todo:
- laser raster
- Laser Inflate jobs uses Endmill Dia not Laser Dia

**Comment by openbuilds-engineer** [comment]
A little sneak.  (; yeah visually its not much, but regular users will remember the browser locking up for a couple seconds. Now 
a) it doesnt lock up as it does the calculations in a seperate thread and
b) it runs them concurrently, not sequencially: more work done in the same time with multiple operations

![WEBWORKERS](https://user-images.githubusercontent.com/31449271/60210010-25cb3b80-985c-11e9-9987-e1d764a2c71a.gif)

**Comment by openbuilds-engineer** [comment]
Went live in https://github.com/OpenBuilds/OpenBuilds-CAM/commit/9b73fc55263ecbc233427ab1e9dd96f0fbd36e3a

**Comment by openbuilds-engineer** [comment]
Bugs: 

TABS broken: https://github.com/OpenBuilds/OpenBuilds-CAM/issues/53
