### ISSUE TITLE
How to make it work offline

### ISSUE THREAD

**Issue by Geekoid85** [OpenBuilds/OpenBuilds-CAM#54]
I tried to clone the project and run the index.html that seems to work fine at first. But I can't generate the gcode after I setup an operation. It loads indefinitely.
![image](https://user-images.githubusercontent.com/38323963/62833290-aabbba00-bc3c-11e9-9eea-d63cb187c6af.png)

The same svg file work fine in the online version.
![image](https://user-images.githubusercontent.com/38323963/62833298-d76fd180-bc3c-11e9-8eb6-59c447a585aa.png)
Also the text feature does not work offline.

I hope that an offline version can be a future option for this software, it's really easy and fluid. I can test more features as the team fix those bugs, I have some basic knowledge of git python and arduino and access to a grbl cnc machine.

**Comment by openbuilds-engineer** [comment]
run it in a local webserver. Chrome doesnt execute scripts from file:// loads

**Comment by openbuilds-engineer** [comment]
Quickest: nodejs + http-server https://www.npmjs.com/package/http-server 
Easier https://www.apachefriends.org/index.html (no need for anything but apache, but easy to install)
