### ISSUE TITLE
Geometry: Merge cannot be changed to "No" once "Yes" is selected

### ISSUE THREAD

**Issue by JinShil** [OpenBuilds/OpenBuilds-CAM#62]
1. Select two paths, and create a pocket operation, choosing "Yes" for the "Geometry: Merge" option, 
2. Press the "Apply and Preview Toolpath" button.
3. Edit the operation and attempt to change the "Geometry: Merge" option to "No".  
4. Press the "Apply and Preview Toolpath" button.
5. Edit the operation and notice the "Geometry: Merge" option is still "Yes"

**Comment by petervanderwalt** [comment]
Thanks for the report will investigate soon

**Comment by petervanderwalt** [comment]
Fixed, will be available later today (Github is doing maintenance on GitHub Pages where CAM is hosted)
