### ISSUE TITLE
Inkscape 1.0 svg resolution

### ISSUE THREAD

**Issue by lolivz** [OpenBuilds/OpenBuilds-CAM#67]
Openbuilds-CAM doesn't import svg files created with Inkscape 1.0 at 96 dpi but uses 90 dpi
In Inkscape 1.0 svg file, there is no `<!-- Created with Inkscape (http://www.inkscape.org/) -->` line in XML Header. If I add this line in the svg, it's ok, files are now imported at 96dpi.

**Comment by petervanderwalt** [comment]
Post a couple sample files please

**Comment by lolivz** [comment]
You'll find 2 identical svg files in this zip : one created with Inkscape 0.92.5, the other with Inkscape 1.0

[inkscape.zip](https://github.com/OpenBuilds/OpenBuilds-CAM/files/4924289/inkscape.zip)

**Comment by petervanderwalt** [comment]
Alright, will check it out. 
Found a header we can fingerprint:  ``` inkscape:version="1.0 (4035a4fb49, 2020-05-01)" ```

**Comment by petervanderwalt** [comment]
Give it a go, and re-open if you have any issues

**Comment by lolivz** [comment]
It's ok now, many thanks !
