### ISSUE TITLE
Importing SVG or DXF

### ISSUE THREAD

**Issue by ChrisBeeson** [OpenBuilds/OpenBuilds-CAM#71]
I'm using illustrator 2020, but I'm really struggling to get SVG or DXF to import correctly.

**DXF:**
> An unknown error occured:TypeError: Cannot read property 'color' of undefined

Happens on every file I try to import.

**SVG:**
Does not import all objects, generally half are missing. I have gone through and made sure paths are closed, and there is no grouping.

Any ideas?

**Comment by petervanderwalt** [comment]
See https://docs.openbuilds.com/doku.php?id=docs:software:file-errors
