### ISSUE TITLE
Vector (no offset) seems broken

### ISSUE THREAD

**Issue by zirkeltraining** [OpenBuilds/OpenBuilds-CAM#80]
A simple open path gets interpreted as closed by the CNC Vector (no Offset) Operation.
Obviously this defeats the purpose (and destroys my object).

<img width="686" alt="image" src="https://user-images.githubusercontent.com/26162293/165711044-dbd8da3e-a821-4317-8992-2aa6875685f7.png">

Could not find a workaround for it. Happens on every single open path i import.
DXF coming from Rhino7 with export settings set to be all polylines, no Arcs.
[test.dxf.zip](https://github.com/OpenBuilds/OpenBuilds-CAM/files/8580974/test.dxf.zip)

(Attaching the DXF here too)

**Comment by petervanderwalt** [comment]
At this time we only really support Closed vectors, sorry!
