### ISSUE TITLE
Feature Request: Adjust Feedrate for small diameter circles

### ISSUE THREAD

**Issue by ImagineerNL** [OpenBuilds/OpenBuilds-CAM#82]
As per this [video by HAAS](https://www.youtube.com/watch?v=6wLU97gVo5k)

Please add an option to the Pocketing Operation to Optionally chose to dynamically adjust the feedrate when doing circles. 
(I understand circles are currently actually segmented lines)
According to the follwing formula:
Feed <sub>(adjusted)</sub> = Feed <sub>(regular)</sub> * (Hole ∅ - Tool ∅) / Hole ∅

Enabling this makes sure you have the correct feedrates for all the smaller circle sizes the toolpath creates when pocketing circles.

**Comment by petervanderwalt** [comment]
happy to accept pull request but would be tricky to do on current codebase
