### ISSUE TITLE
Feature Request: Option to Pocket XY before Z

### ISSUE THREAD

**Issue by ImagineerNL** [OpenBuilds/OpenBuilds-CAM#83]
Current Pocketing Operation is Z before XY
[Z-before-XY.gcode.txt](https://github.com/OpenBuilds/OpenBuilds-CAM/files/9690213/Z-before-XY.gcode.txt)

- Z 0
- Step down Z, 
- XY of slot1 in Pocket
- Step down Z,
- XY slot1 Pocket 1
- Repeat until final depth
- Z 0 S
- Step down Z
- XY of slot2 Pocket
- Stepdown Z, etc.

For chip clearing and visibilty on the toolpath in the work, it would be great to be able to chose to do XY before Z

- Stepdown Z
- Pocket XY all 'slots' 
- Stepdown Z
- repeat until at depth

**Comment by petervanderwalt** [comment]
not at this ti,e, happy to accept pull request if coded
