### ISSUE TITLE
Strange  shapes when converting DXF circles to GCode  

### ISSUE THREAD

**Issue by Ger-55** [OpenBuilds/OpenBuilds-CAM#86]
When importing a circle in DXF format in Openbuilds CAM  circles flattens as shown in the figure. The DXF file is OK. Adding extra anchorpoints around the circle ( I use Adobe Illustrator ) does not help.  Looking at the GCode I see that a circle is approximated by very small straight segments. This is a basic but not the best solution  since GCode supports cubic splines so a circle/ellipse can be written e.g. as a four  segments using four  G4 statements. and 4 coordinate pairs. 
       
[circleTest.dxf.txt](https://github.com/OpenBuilds/OpenBuilds-CAM/files/10874006/circleTest.dxf.txt)

![capture_004_28022023_185249](https://user-images.githubusercontent.com/60196516/222502889-9fbd6530-1083-440e-9bc2-f5df87138bbe.jpg)

![capture_002_28022023_180840](https://user-images.githubusercontent.com/60196516/222502874-a488dc40-3c55-4487-a646-c98ccfb447bb.jpg)

![capture_003_28022023_184957](https://user-images.githubusercontent.com/60196516/222502862-63faf663-222e-4a85-a932-b96c409e54e1.jpg)

**Comment by petervanderwalt** [comment]
Just give it clean files per https://docs.openbuilds.com/doku.php?id=docs:software:file-errors
