### ISSUE TITLE
incorect objects while importing DXF file

### ISSUE THREAD

**Issue by petrasl1976** [OpenBuilds/OpenBuilds-CAM#87]
i am getting incorrect objects (arcs bend to opposite side that original) drawn while importing DXF file. I use OnShape to draw and export DXF

<img width="791" alt="imported" src="https://user-images.githubusercontent.com/30649191/222984857-0a4000d9-6428-4cff-b117-a31d2f49d553.png">
<img width="857" alt="Original" src="https://user-images.githubusercontent.com/30649191/222984858-e1292914-b625-4753-83e0-256d2e71bb27.png">

Could it be that i exporting it incorrectly?

**Comment by Ger-55** [comment]
Hi, i have the same problem with circles in Openbuilds CAM.  You can check you dxf file with a Dxf viewer program . I use Adobe Illustrator for design and the dxf is ok but CAM messes up things. The Gcode commands to draw curves are rather complex .

**Comment by petrasl1976** [comment]
DXF viewers show properly. I think issue is with the OpenBuilds CAM while displaying it.

**Comment by Ger-55** [comment]
As far as I know OpenBuilds CAM converts arc segments into small straight lines, and there things go wrong. Unfortunately I have very little knowledge on JavaScript so checking the source code for this is not for me.

**Comment by Majormakes** [comment]
any solution to this problem, still enduring the same issue

**Comment by petervanderwalt** [comment]
Just give it clean files per https://docs.openbuilds.com/doku.php?id=docs:software:file-errors
