### ISSUE TITLE
Not working from local webhost directory

### ISSUE THREAD

**Issue by MarcinKlima** [OpenBuilds/OpenBuilds-CAM#92]
Hi the OpenBuilds-CAM don`t work from local directory like ... **http://192.168.1.1/~user/obcam** running on Apache 2.4. 
On this same configuration with virtualhost and redirected domain, work perfect. 
Need to run it on CNC machine  with webserver without domain etc, only possible is like http://local_ip/~user/somedir.  
**Errors:**
The first, showing when select Document->Layer/etc :
An unknown error occured:TypeError: child.userData.layer is undefined
And next, is showing when try to generate any toolpatch, when the error is happen gcode status: Unavaliable please wait..  
An unknown error occured:NetworkError: A network error occurred.

What to do ? :)

**Comment by petervanderwalt** [comment]
check dev console logs. 
unable to assist with custom install / dev
