### ISSUE TITLE
Endless ver. check errors.

### ISSUE THREAD

**Issue by AlanSims** [OpenBuilds/OpenBuilds-CAM#94]
Is there a solution to this error that is happening about every 2 seconds? I'm hoping to improve performance of this AWESOME little app.
jquery.min.js:4 
        
        
       GET https://mymachine.openbuilds.com:3001/api/version?_=1702210392318 net::ERR_CONNECTION_REFUSED
send @ jquery.min.js:4
ajax @ jquery.min.js:4
checkIfDriverIsInstalled @ integration-machine-driver.js:4
(anonymous) @ integration-machine-driver.js:8

**Comment by petervanderwalt** [comment]
no solution as we intend reimplimenting transfer, temporarilly disabled while CONTROL updates were unavailable
